export const siteAssetManifest = [
  "/assets/mainback3.png",
  "/assets/mobileback1.svg",
  "/assets/cloudy2.png",
  "/assets/monarch.png",
  "/assets/tv.png",
  "/assets/multimodal.png",
  "/assets/ps.png",
  "/assets/rs.png",
  "/assets/ms.png",
  "/assets/ma1.svg",
  "/assets/is1.svg",
  "/assets/gm1.svg",
  "/assets/scl.svg",
  "/assets/me.svg",
  "/assets/linkedin.svg",
  "/assets/github.svg",
  "/assets/instagram.svg",
  "/assets/gmail.svg",
  "/assets/butterfly1.svg",
  "/assets/butterfly2.svg",
  "/assets/butterfly3.svg",
  "/assets/butterfly4.svg",
  "/assets/butterfly1(inverted).svg",
  "/assets/butterfly2(inverted).svg",
  "/assets/butterfly3(inverted).svg",
  "/assets/butterfly4(inverted).svg",
] as const;
